"""Seed initial challenge types and achievements

Revision ID: 002_seed_data
Revises: 001_initial
Create Date: 2026-02-28 00:01:00.000000

"""
from typing import Sequence, Union
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

revision: str = "002_seed_data"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOW = datetime.now(timezone.utc).isoformat()


def upgrade() -> None:
    # ── Challenge Types (CHM_KRYPTON планы) ────────────────────────────────────
    op.bulk_insert(
        sa.table(
            "challenge_types",
            sa.column("name", sa.String),
            sa.column("description", sa.Text),
            sa.column("rank_icon", sa.String),
            sa.column("gradient_bg", sa.String),
            sa.column("account_size", sa.Numeric),
            sa.column("price", sa.Numeric),
            sa.column("profit_target_p1", sa.Numeric),
            sa.column("profit_target_p2", sa.Numeric),
            sa.column("max_daily_loss", sa.Numeric),
            sa.column("max_total_loss", sa.Numeric),
            sa.column("min_trading_days", sa.Integer),
            sa.column("max_trading_days", sa.Integer),
            sa.column("drawdown_type", sa.String),
            sa.column("consistency_rule", sa.Boolean),
            sa.column("news_trading_ban", sa.Boolean),
            sa.column("is_one_phase", sa.Boolean),
            sa.column("is_instant", sa.Boolean),
            sa.column("is_refundable", sa.Boolean),
            sa.column("max_leverage", sa.Integer),
            sa.column("phase1_mode", sa.String),
            sa.column("phase2_mode", sa.String),
            sa.column("funded_mode", sa.String),
            sa.column("profit_split_pct", sa.Numeric),
            sa.column("is_active", sa.Boolean),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "name": "Isotope $5K",
                "description": "Путь новичка. Нестабильный изотоп в поиске своей реакции.",
                "rank_icon": "/assets/ranks/isotope.webm",
                "gradient_bg": "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
                "account_size": 5000,
                "price": 49,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": False,
                "news_trading_ban": False,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": False,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 80,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
            {
                "name": "Reagent $10K",
                "description": "Начало реакции. Трейдер вступает в игру.",
                "rank_icon": "/assets/ranks/reagent.webm",
                "gradient_bg": "linear-gradient(135deg, #0f3460 0%, #16213e 100%)",
                "account_size": 10000,
                "price": 89,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": False,
                "news_trading_ban": False,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": False,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 80,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
            {
                "name": "Catalyst $25K",
                "description": "Катализатор роста. Профессиональный уровень.",
                "rank_icon": "/assets/ranks/catalyst.webm",
                "gradient_bg": "linear-gradient(135deg, #533483 0%, #1a1a2e 100%)",
                "account_size": 25000,
                "price": 199,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": True,
                "news_trading_ban": False,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": False,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 80,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
            {
                "name": "Molecule $50K",
                "description": "Системный трейдер. Связность и последовательность.",
                "rank_icon": "/assets/ranks/molecule.webm",
                "gradient_bg": "linear-gradient(135deg, #6c63ff 0%, #1a1a2e 100%)",
                "account_size": 50000,
                "price": 349,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": True,
                "news_trading_ban": False,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": False,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 80,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
            {
                "name": "Crystal $100K",
                "description": "Чистая структура. Дисциплина на высшем уровне.",
                "rank_icon": "/assets/ranks/crystal.webm",
                "gradient_bg": "linear-gradient(135deg, #00d4aa 0%, #0f3460 100%)",
                "account_size": 100000,
                "price": 599,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": True,
                "news_trading_ban": True,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": True,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 85,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
            {
                "name": "Nucleus $200K",
                "description": "Ядро капитала. Для элиты трейдинга.",
                "rank_icon": "/assets/ranks/nucleus.webm",
                "gradient_bg": "linear-gradient(135deg, #ffa502 0%, #1a1a2e 100%)",
                "account_size": 200000,
                "price": 1099,
                "profit_target_p1": 8,
                "profit_target_p2": 5,
                "max_daily_loss": 5,
                "max_total_loss": 10,
                "min_trading_days": 5,
                "max_trading_days": None,
                "drawdown_type": "trailing",
                "consistency_rule": True,
                "news_trading_ban": True,
                "is_one_phase": False,
                "is_instant": False,
                "is_refundable": True,
                "max_leverage": 50,
                "phase1_mode": "demo",
                "phase2_mode": "demo",
                "funded_mode": "real",
                "profit_split_pct": 90,
                "is_active": True,
                "created_at": NOW,
                "updated_at": NOW,
            },
        ],
    )

    # ── Achievements (20 уникальных достижений) ────────────────────────────────
    op.bulk_insert(
        sa.table(
            "achievements",
            sa.column("key", sa.String),
            sa.column("name_ru", sa.String),
            sa.column("description_ru", sa.Text),
            sa.column("lottie_file", sa.String),
            sa.column("levels_config", sa.JSON),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "key": "sniper",
                "name_ru": "Снайпер",
                "description_ru": "5 сделок подряд с RR ≥ 2",
                "lottie_file": "/assets/achievements/sniper.lottie",
                "levels_config": {"bronze": 5, "silver": 10, "gold": 25, "platinum": 50},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "diamond_hands",
                "name_ru": "Алмазные руки",
                "description_ru": "Удержание прибыльной позиции более 24 часов",
                "lottie_file": "/assets/achievements/diamond_hands.lottie",
                "levels_config": {"bronze": 1, "silver": 5, "gold": 10, "platinum": 25},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "rocketeer",
                "name_ru": "Ракетчик",
                "description_ru": "+3% PNL за один торговый день",
                "lottie_file": "/assets/achievements/rocketeer.lottie",
                "levels_config": {"bronze": 1, "silver": 3, "gold": 7, "platinum": 15},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "guardian",
                "name_ru": "Страж капитала",
                "description_ru": "Ни одного нарушения за весь период испытания",
                "lottie_file": "/assets/achievements/guardian.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "strategist",
                "name_ru": "Стратег",
                "description_ru": "Соотношение прибыльных/убыточных сделок > 60%",
                "lottie_file": "/assets/achievements/strategist.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "scalper",
                "name_ru": "Скальпер",
                "description_ru": "20+ сделок за один торговый день",
                "lottie_file": "/assets/achievements/scalper.lottie",
                "levels_config": {"bronze": 1, "silver": 3, "gold": 7, "platinum": 15},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "night_wolf",
                "name_ru": "Ночной волк",
                "description_ru": "Торговля с 00:00 до 06:00 UTC",
                "lottie_file": "/assets/achievements/night_wolf.lottie",
                "levels_config": {"bronze": 1, "silver": 5, "gold": 10, "platinum": 20},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "legend",
                "name_ru": "Легенда",
                "description_ru": "Успешное прохождение счёта $200,000",
                "lottie_file": "/assets/achievements/legend.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "first_blood",
                "name_ru": "Первая кровь",
                "description_ru": "Первая прибыльная сделка на платформе",
                "lottie_file": "/assets/achievements/first_blood.lottie",
                "levels_config": {"bronze": 1, "silver": 1, "gold": 1, "platinum": 1},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "streak_master",
                "name_ru": "Мастер серии",
                "description_ru": "Торговля без нарушений N дней подряд",
                "lottie_file": "/assets/achievements/streak_master.lottie",
                "levels_config": {"bronze": 5, "silver": 10, "gold": 20, "platinum": 30},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "consistent",
                "name_ru": "Консистентный",
                "description_ru": "Прибыльные сделки 5 дней подряд",
                "lottie_file": "/assets/achievements/consistent.lottie",
                "levels_config": {"bronze": 5, "silver": 10, "gold": 15, "platinum": 20},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "diversified",
                "name_ru": "Диверсификатор",
                "description_ru": "Прибыльные сделки по 5+ разным парам",
                "lottie_file": "/assets/achievements/diversified.lottie",
                "levels_config": {"bronze": 5, "silver": 10, "gold": 15, "platinum": 20},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "funded_elite",
                "name_ru": "Финансированная элита",
                "description_ru": "Получение funded счёта впервые",
                "lottie_file": "/assets/achievements/funded_elite.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "scaled",
                "name_ru": "Масштабированный",
                "description_ru": "Первое увеличение счёта через масштабирование",
                "lottie_file": "/assets/achievements/scaled.lottie",
                "levels_config": {"bronze": 1, "silver": 3, "gold": 5, "platinum": 10},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "referral_master",
                "name_ru": "Мастер рефералов",
                "description_ru": "Привёл N рефералов на платформу",
                "lottie_file": "/assets/achievements/referral_master.lottie",
                "levels_config": {"bronze": 1, "silver": 5, "gold": 10, "platinum": 25},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "risk_manager",
                "name_ru": "Риск-менеджер",
                "description_ru": "Никогда не превышал 2% дневной просадки",
                "lottie_file": "/assets/achievements/risk_manager.lottie",
                "levels_config": {"bronze": 5, "silver": 10, "gold": 20, "platinum": 30},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "swift_trader",
                "name_ru": "Быстрый трейдер",
                "description_ru": "Прохождение Phase 1 менее чем за 7 дней",
                "lottie_file": "/assets/achievements/swift_trader.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "bull_bear",
                "name_ru": "Быки и медведи",
                "description_ru": "Прибыльные сделки как в лонг, так и в шорт за один день",
                "lottie_file": "/assets/achievements/bull_bear.lottie",
                "levels_config": {"bronze": 1, "silver": 5, "gold": 10, "platinum": 20},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "iron_discipline",
                "name_ru": "Железная дисциплина",
                "description_ru": "Максимальный drawdown менее 3% за всё испытание",
                "lottie_file": "/assets/achievements/iron_discipline.lottie",
                "levels_config": {"bronze": 1, "silver": 2, "gold": 3, "platinum": 5},
                "created_at": NOW, "updated_at": NOW,
            },
            {
                "key": "krypton_rank",
                "name_ru": "Благородный газ",
                "description_ru": "Достижение ранга Krypton — максимального уровня платформы",
                "lottie_file": "/assets/achievements/krypton_rank.lottie",
                "levels_config": {"bronze": 1, "silver": 1, "gold": 1, "platinum": 1},
                "created_at": NOW, "updated_at": NOW,
            },
        ],
    )


def downgrade() -> None:
    op.execute("DELETE FROM achievements")
    op.execute("DELETE FROM challenge_types")
